/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
pluginManagement {
    val springBootVersion = providers.gradleProperty("springBootVersion").get()
    val springDependencyManagementVersion = providers.gradleProperty("springDependencyManagementVersion").get()
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id("org.springframework.boot") version springBootVersion
        id("io.spring.dependency-management") version springDependencyManagementVersion
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // 1) 오픈소스를 위한 중앙 저장소
        mavenCentral()
        //2) 사내 Nexus 저장소
        val allowInsecure = providers.gradleProperty("nexus.allowInsecure")
            .orNull
            ?.toBoolean() ?: false 
        providers.gradleProperty("nexus.releasesUrl").orNull?.let { url ->
            maven(url) {
                name = "podosoftware-nexus-releases"
                isAllowInsecureProtocol = allowInsecure 
            }
        }
        // providers.gradleProperty("nexus.snapshotsUrl").orNull?.let { url ->
        //     maven(url) {
        //         name = "podosoftware-nexus-snapshots"
        //         isAllowInsecureProtocol = allowInsecure
        //     }
        // } 
    }
}
rootProject.name = "studio-one-forums"
include("starter")
